### ISSUE TITLE
php8 ReflectionUnionType not working for "hasLaravelCollection"

### ISSUE THREAD

**Issue by fcaps** [spatie/laravel-typescript-transformer#11]
Hey,
cannot share the actual project code, but maybe we have some time later to make it reproducible for you guys.
Version: spatie/laravel-typescript-transformer:2.0.0
  
    Call to undefined method ReflectionUnionType::getName()
  
    at vendor/spatie/laravel-typescript-transformer/src/TypeProcessors/LaravelCollectionTypeProcessor.php:73
       69▕ //
       70▕ //            return false;
       71▕ //        }
       72▕ 
    ➜  73▕         return is_a($type->getName(), Enumerable::class, true);
       74▕     }
       75▕ 
       76▕     private function replaceLaravelCollectionInCompound(Compound $compound): Compound
       77▕     {

The case for "instanceof ReflectionUnionType" is missing here (simple loop over ReflectionUnionType::getTypes())

**Comment by rubenvanassche** [comment]
Hi @fcaps,

This issue should be fixed with version 2.1.0!
