### ISSUE TITLE
Running the command results in Class "Spatie\Enum\Enum" does not exist.

### ISSUE THREAD

**Issue by nonetallt** [spatie/laravel-typescript-transformer#23]
Package version: `2.1.7`
Laravel version: `v10.1.5`

As stated in the description, `php artisan typescript:transform` results in `Class "Spatie\Enum\Enum" does not exist.`

I'm getting this error after putting the `@typescript` annotation on a Laravel Notification class. Without the annotation the command simply outputs and empty table.

**Comment by nonetallt** [comment]
I made another attempt to execute the transform without having to use the command and got a proper error stack trace as a result:

```php
   ReflectionException 

  Class "Spatie\Enum\Enum" does not exist

  at vendor/spatie/typescript-transformer/src/Transformers/SpatieEnumTransformer.php:18
     14▕     }
     15▕ 
     16▕     public function transform(ReflectionClass $class, string $name): ?TransformedType
     17▕     {
  ➜  18▕         if ($class->isSubclassOf(Enum::class) === false) {
     19▕             return null;
     20▕         }
     21▕ 
     22▕         return $this->config->shouldTransformToNativeEnums()

      [2m+6 vendor frames [22m
  7   app/Console/Commands/PublishEventTypesCommand.php:51
      Spatie\TypeScriptTransformer\TypeScriptTransformer::transform()

      [2m+13 vendor frames [22m
  21  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

```

**Comment by nonetallt** [comment]
Fixed by changing the default `SpatieEnumTransfomer` to `EnumTransformer`. I don't think this package should use a transformer that requires another package to be installed as a default config value.

**Comment by rubenvanassche** [comment]
Yeah, I agree with you. But this requires a major update. We're currently working on the next version of typescript-transformer and that should remove the spatie enum transformer and replace it with the native enum transformer.

That being said, I've tagged v2.2 with the native enum transformer before the spatie one. That should already fix the problem you we're having.

**Comment by MotionPhix** [comment]
In a newly created Laravel 11 project, I am still experiencing this issue. It just says *Class "Spatie\Enum\Enum" does not exist* and no traces at all.  The following is how I have ordered my transformers in the typescript-transformer config file:

```
'transformers' => [
        Spatie\LaravelTypeScriptTransformer\Transformers\SpatieStateTransformer::class,
        Spatie\TypeScriptTransformer\Transformers\EnumTransformer::class,
        Spatie\TypeScriptTransformer\Transformers\SpatieEnumTransformer::class,
        Spatie\LaravelTypeScriptTransformer\Transformers\DtoTransformer::class,
        Spatie\LaravelData\Support\TypeScriptTransformer\DataTypeScriptTransformer::class,
    ],
```

What could I be doing wrong? This happens when I add typescript notation to data classes like in the following example:

```
<?php

namespace App\Data;

use App\Enums\AddressType;
use Spatie\LaravelData\Data;
use Spatie\TypeScriptTransformer\Attributes\TypeScript;

/** @typescript **/
class AddressData extends Data
{
    public function __construct(
        public ?int $id,
        public AddressType $type,
        public string $street,
        public string $city,
        public ?string $state,
        public string $country,
    ) {}
}
```

If I remove the typescript notation it works without error, only producing types for enum classes, no data classes.

```
<?php

namespace App\Data;

use App\Enums\AddressType;
use Spatie\LaravelData\Data;
use Spatie\TypeScriptTransformer\Attributes\TypeScript;

class AddressData extends Data
{
    public function __construct(
        public ?int $id,
        public AddressType $type,
        public string $street,
        public string $city,
        public ?string $state,
        public string $country,
    ) {}
}
```

**Comment by laxit-patel** [comment]
ran into exact same situation as @MotionPhix , simply commented that specific transformer and it worked!
```php
    'transformers' => [
        Spatie\LaravelTypeScriptTransformer\Transformers\SpatieStateTransformer::class,
        Spatie\TypeScriptTransformer\Transformers\EnumTransformer::class,
//        Spatie\TypeScriptTransformer\Transformers\SpatieEnumTransformer::class,
        Spatie\LaravelTypeScriptTransformer\Transformers\DtoTransformer::class,
    ],
```
