### ISSUE TITLE
Permission denied on file_get_contents

### ISSUE THREAD

**Issue by DerkJanSpeelman** [spatie/laravel-typescript-transformer#3]
I'm trying to run `php artisan typescript:transform`, but I'm getting this error:

```
file_get_contents(<root>\app\Console): failed to open stream: Permission denied
```

**Here's what I did:**

I read the documentation on https://spatie.be/docs/typescript-transformer/v1/laravel/installation-and-setup and https://spatie.be/docs/typescript-transformer/v1.

I also checked the permissions of my app/Console folder, storage, app, everything. I also cleared all php cache (https://tecadmin.net/clear-cache-laravel-5/) and ran `composer dump-autoload`.

**Comment by freekmurze** [comment]
The tests of our package seems to run fine. It also work locally. So my guess that this is an permissions issue on your machine.

We'd accept a PR should you find that the package does cause the problem on your particular setup.

**Comment by DerkJanSpeelman** [comment]
I was running the command outside my docker container (in my local files). Usually this goes well.

My bad! The package is working perfectly! Thank you
