### ISSUE TITLE
Unique rule breaks typescript transformation

### ISSUE THREAD

**Issue by KKSzymanowski** [spatie/laravel-typescript-transformer#37]
Given the following data object:
```php
#[TypeScript]
class UpdateDictionaryData extends Data
{
    public function __construct(
        #[IntegerType]
        #[Unique('dictionaries', ignore: new RouteParameterReference('dictionary', 'id'))]
        public ?string $dms_id,
        // Other fields
    )
}
```
when I run `php artisan typescript:transform` I get the following error:
```php
Cannot find route parameter dictionary with property id
```
I don't get any stack trace but the exception is thrown in `RouteParameterReference::getValue()`

**Comment by rubenvanassche** [comment]
I'm unable to reproduce this (data v4), could you try it with that version?

If it still fails, please open an new issue with a test project that demonstrates the issue.

**Comment by rubenvanassche** [comment]
Was able to reproduce it in antoher case, gonna take a look at it

**Comment by KKSzymanowski** [comment]
@rubenvanassche Have you had any luck with this? Is there anything I can do to help?

**Comment by rubenvanassche** [comment]
Yeah it should be fixed with the newest version of laravel-data
