### ISSUE TITLE
Upgrade to spatie/laravel-data v4 breaks nested object definitions with keys

### ISSUE THREAD

**Issue by sebastiaanluca** [spatie/laravel-typescript-transformer#39]
Bit of an odd title, but let me explain.

With spatie/laravel-data v3, we could generate definitions of arrays with keys, aka regular objects in JS/TS. This is explained in the documentation: https://spatie.be/docs/typescript-transformer/v2/dtos/typing-properties#content-transforming-arrays (arrays vs objects).

Data object properties:

```php
/** @var array<int,\App\NestedData> */
public readonly array $array5,
/** @var array<string,\App\NestedData> */
public readonly array $array6,
```

Generated definition; notice `array5` and `array6`:

```ts
declare namespace App {
export type NestedData = {
title: string;
};
export type PostData = {
title: string;
content: string;
array1: Array<string>;
array2: Array<string>;
array3: { [key: string]: string };
array4: { [key: number]: string };
array5: { [key: string]: App.NestedData };
array6: { [key: string]: App.NestedData };
};
}
```

In v4, we now get regular arrays (`array5` and `array6`):

```ts
declare namespace App {
export type NestedData = {
title: string;
};
export type PostData = {
title: string;
content: string;
array1: Array<string>;
array2: Array<string>;
array3: { [key: string]: string };
array4: { [key: number]: string };
array5: Array<App.NestedData>;
array6: Array<App.NestedData>;
};
}
```

Reproduced this in a fresh project: https://github.com/sebastiaanluca/spatie-data-typescript-arrayobject-bug. See https://github.com/sebastiaanluca/spatie-data-typescript-arrayobject-bug/commit/c701de25523f49dabdb7efbeb9308a96938d6ab3 for the reproduction.

Still debugging where exactly the change lies and how to fix it.

I've posted this here since it concerns generating TS definitions from data objects.

**Comment by sebastiaanluca** [comment]
In `\Spatie\TypeScriptTransformer\Actions\TranspileTypeToTypeScriptAction::isTypeScriptArray()`, it incorrectly identifies the property as a regular array instead of an object. If I remove the check in `\Spatie\TypeScriptTransformer\Actions\TranspileTypeToTypeScriptAction::resolveListType()` it falls back to the keyed object/array and works ok.

It also somehow determines that the keys are `string | number`:

```
phpDocumentor\Reflection\Types\Compound^ {#7130
  -types: array:2 [
    0 => phpDocumentor\Reflection\Types\String_^ {#7129}
    1 => phpDocumentor\Reflection\Types\Integer^ {#7128}
  ]
  -token: "|"
} // vendor/spatie/typescript-transformer/src/Actions/TranspileTypeToTypeScriptAction.php:138
```

**Comment by rubenvanassche** [comment]
When we've got the time for it, you're always welcome to send in a PR to laravel-data fixing this.

**Comment by sebastiaanluca** [comment]
@rubenvanassche I'll be glad to submit a PR, but after debugging I have no idea what's causing it 😅 It's following the path of `$dataClass` instead of array/collection/…, so any further steps to build the TypeScript definitions correctly are bypassed. I can switch those around to make it work, but I have no idea what the impact is on the functionality of the package. Would appreciate some guidance as you have a better view on it.

**Comment by rubenvanassche** [comment]
Hi @sebastiaanluca,

Take a look at the transformer within the data package, that one is being used. I've added some extra functionality a few days ago which parses the keys of annotations, so that these are progated correctly. Somehow those should be incorporated when generating typescript properties.

**Comment by rubenvanassche** [comment]
If I'm not mistaken this is fixed because I've had the same problem in one of my own projects so I've Pr'ed it.
