### ISSUE TITLE
Laravel models

### ISSUE THREAD

**Issue by MatanYadaev** [spatie/laravel-typescript-transformer#4]
Is this package can transform Laravel models as well? If not, there's a plan to implement it?

BTW, great package!

**Comment by Gummibeer** [comment]
It would need a new transformer. The major problem would be to resolve all the columns - with a fully annotated doc-block like [ide-helper](https://github.com/barryvdh/laravel-ide-helper) generates it this would be a lot easier I think!? 🤔

**Comment by freekmurze** [comment]
Closing this for now, as we don't need this for our current project. 

But feel free to submit a fully tested and documented PR for this.

**Comment by basbart** [comment]
@MatanYadaev I had this issue myself, ended up using the database schema to generate dummy classes with properties. I wrote a custom transformer which utilises these dummy classes for property extraction instead of the eloquent model itself.

**Comment by rubenvanassche** [comment]
Hi @basbart,

Would it be possible to show some of the code you've written? I'm quite curious about how you solved it! And maybe we could add such a transformer by default in the package.

Ruben

**Comment by basbart** [comment]
Hi @rubenvanassche,

Ofcourse, happy to help. See the 2 gists below.

The command where everything gets executed:
[](https://gist.github.com/basbart/5d9479169ed98f10713d493c5baa49fb
)
The transformer: 
[](https://gist.github.com/basbart/65e9541d49ae7193846a309bb2515120)
