### ISSUE TITLE
DataTypeScriptTransformer ignore LiteralTypeScriptType

### ISSUE THREAD

**Issue by mshamaseen** [spatie/laravel-typescript-transformer#48]
**✏️ Describe the bug**
when DataTypeScriptTransformer is added to config/typescript-transformer.php, any LiteralTypeScriptType attribute on a collection will be ignored.

**↪️ To Reproduce**
See code bellow

```php
class MyData extends Data
{
    public function __construct(
        public string $title,
        /**
         * @var Collection<int, UrlButton|CallButton>
         */
        #[WithCast(ButtonCaster::class)]
        #[LiteralTypeScriptType('Array<UrlButton|CallButton>')]
        public Collection $buttons = new Collection()
    ) {
    }
}
```

now run transform.

**✅ Expected behavior**
buttons type is expected to respect LiteralTypeScriptType and to be equal to Array<UrlButton|CallButton>
but the result is `buttons: Array<UrlButton>`

**🖥️ Versions**

Laravel: 10
Laravel Data: 4.8
PHP: 8.1

**Comment by rubenvanassche** [comment]
Mhh get your point this is because the DataTransformer for TypeScript Transformer doesn't really follow the rules and writes its own output. In TypeScript transformer 3 this all changes and then this should be possible, you'll just have to wait a few more weeks 😅
